import type { Submission } from './types'
import { analyzeRisk } from './moderation'

const now = new Date()
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000)

const raw: Omit<Submission, 'riskLevel' | 'moderationFlags'>[] = [
  {
    id: 'sub_001',
    submitterName: 'Anonymous',
    submitterProgram: 'IPM',
    submitterBatch: '2027',
    targetName: 'A certain professor',
    targetProgram: 'Prof.',
    targetBatch: "Don't know",
    category: 'Frustration',
    bodyText: 'The way this professor gives marks is so inconsistent it actually makes me want to cry. My friend wrote almost the same answer and got 18/20 while I got 9/20. When I asked for re-evaluation I was told "the evaluation is final". This is not education, this is pure luck.',
    triggerFlag: 'No',
    status: 'pending',
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(2),
  },
  {
    id: 'sub_002',
    submitterName: 'Anonymous',
    submitterProgram: 'MBA',
    submitterBatch: '2026',
    targetName: 'A batchmate',
    targetProgram: 'MBA',
    targetBatch: '2026',
    category: 'Confession',
    bodyText: 'I have a huge crush on someone in my cohort and every group project we get assigned together feels like both heaven and torture. I keep rehearsing conversations in my head that I never actually have. This is embarrassing to admit but I had to tell someone.',
    triggerFlag: 'No',
    status: 'approved',
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(4),
    approvedAt: hoursAgo(4),
  },
  {
    id: 'sub_003',
    submitterName: 'Anonymous',
    submitterProgram: 'MBA-BA',
    submitterBatch: '2025',
    targetName: 'Campus canteen staff',
    targetProgram: 'Other',
    targetBatch: "Don't know",
    category: 'Horror Story / Weird Experiences',
    bodyText: 'Found something unidentifiable in my dal last week. When I told the counter person they just shrugged and said "it happens." I have not been back since. The students deserve better than this level of quality control.',
    triggerFlag: 'No',
    status: 'pending',
    createdAt: hoursAgo(8),
    updatedAt: hoursAgo(8),
  },
  {
    id: 'sub_004',
    submitterName: 'Anonymous',
    submitterProgram: 'PhD',
    submitterBatch: '2025',
    targetName: 'A senior batch student',
    targetProgram: 'MBA',
    targetBatch: '2025',
    category: 'Gossip',
    bodyText: "Apparently someone submitted a case study that was basically lifted word for word from a Harvard case note with just minor paraphrasing. The prof didn't notice. The student got an A. Some of us actually stayed up three nights writing ours from scratch.",
    triggerFlag: 'Maybe',
    status: 'pending',
    createdAt: hoursAgo(12),
    updatedAt: hoursAgo(12),
  },
  {
    id: 'sub_005',
    submitterName: 'Anonymous',
    submitterProgram: 'MBA-HR',
    submitterBatch: '2026',
    targetName: 'Campus administration',
    targetProgram: 'Other',
    targetBatch: "Don't know",
    category: 'Feedback',
    bodyText: "The mental health resources on campus are severely underutilized because students don't trust that it's anonymous. Can we please have an actual external counselor who isn't affiliated with the institution? The number of people quietly struggling is much higher than anyone realizes.",
    triggerFlag: 'Yes',
    status: 'approved',
    createdAt: hoursAgo(16),
    updatedAt: hoursAgo(14),
    approvedAt: hoursAgo(14),
  },
  {
    id: 'sub_006',
    submitterName: 'Anonymous',
    submitterProgram: 'IPM',
    submitterBatch: '2028',
    targetName: 'A classmate',
    targetProgram: 'IPM',
    targetBatch: '2028',
    category: 'Confession',
    bodyText: "I let my best friend take credit for an idea that was mine because I was too scared of being judged in the group. They got praised in front of everyone and I just smiled. I'm still angry at myself for not speaking up.",
    triggerFlag: 'No',
    status: 'posted',
    createdAt: hoursAgo(30),
    updatedAt: hoursAgo(25),
    approvedAt: hoursAgo(28),
    postedAt: hoursAgo(25),
  },
  {
    id: 'sub_007',
    submitterName: 'Anonymous',
    submitterProgram: 'MBA',
    submitterBatch: '2026',
    targetName: 'Group project members',
    targetProgram: 'MBA',
    targetBatch: '2026',
    category: 'Frustration',
    bodyText: 'Our group of 6 has 4 people who have done literally nothing this entire term. The two of us who are actually doing the work are about to just submit with our names only. If you recognize yourself in this, please know we see you.',
    triggerFlag: 'No',
    status: 'pending',
    createdAt: hoursAgo(3),
    updatedAt: hoursAgo(3),
  },
  {
    id: 'sub_008',
    submitterName: 'Anonymous',
    submitterProgram: 'MBA-BA',
    submitterBatch: '2026',
    targetName: 'A faculty member',
    targetProgram: 'Prof.',
    targetBatch: "Don't know",
    category: 'Good/Bad Experiences',
    bodyText: "I want to genuinely thank one professor who noticed I was struggling in week 3 and quietly pulled me aside after class just to check in. They didn't make it a big deal, didn't involve anyone else, and just listened. That meant more than any grade.",
    triggerFlag: 'No',
    status: 'approved',
    createdAt: hoursAgo(20),
    updatedAt: hoursAgo(18),
    approvedAt: hoursAgo(18),
  },
  {
    id: 'sub_009',
    submitterName: 'Anonymous',
    submitterProgram: 'IPM',
    submitterBatch: '2027',
    targetName: 'A hostel warden',
    targetProgram: 'Other',
    targetBatch: "Don't know",
    category: 'Horror Story / Weird Experiences',
    bodyText: 'The warden knocked at 11:30 PM to check if we were "making noise" and then stood outside the door for 10 minutes in complete silence. We were studying. Just studying. Why was this so unsettling? Campus life is a fever dream.',
    triggerFlag: 'No',
    status: 'pending',
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(6),
  },
  {
    id: 'sub_010',
    submitterName: 'Anonymous',
    submitterProgram: 'MBA-HR',
    submitterBatch: '2025',
    targetName: 'Placement cell',
    targetProgram: 'Other',
    targetBatch: "Don't know",
    category: 'Feedback',
    bodyText: 'The placement data released publicly does not match what students are privately discussing. Median salary figures feel optimistic at best. I understand the pressure to market the program but misleading prospective students is ethically wrong.',
    triggerFlag: 'No',
    status: 'rejected',
    createdAt: hoursAgo(48),
    updatedAt: hoursAgo(45),
    rejectedAt: hoursAgo(45),
  },
  {
    id: 'sub_011',
    submitterName: 'Anonymous',
    submitterProgram: 'MBA',
    submitterBatch: '2025',
    targetName: 'A study group member',
    targetProgram: 'MBA',
    targetBatch: '2025',
    category: 'Advice',
    bodyText: "Stop waiting until the night before to start assignments. I know everyone acts like it's fine but the 2 AM panic submissions are causing real damage to your health. Your future self will thank you for starting even two days early.",
    triggerFlag: 'No',
    status: 'posted',
    createdAt: hoursAgo(72),
    updatedAt: hoursAgo(65),
    approvedAt: hoursAgo(68),
    postedAt: hoursAgo(65),
  },
  {
    id: 'sub_012',
    submitterName: 'Anonymous',
    submitterProgram: 'IPM',
    submitterBatch: '2029',
    targetName: 'Senior batch students',
    targetProgram: 'IPM',
    targetBatch: '2027',
    category: 'Good/Bad Experiences',
    bodyText: "First week seniors were so welcoming it almost felt fake. Third week I asked for help with a subject and was told to \"figure it out yourself, that's how you learn.\" So apparently the welcoming vibe had an expiry date.",
    triggerFlag: 'No',
    status: 'pending',
    createdAt: hoursAgo(4),
    updatedAt: hoursAgo(4),
  },
  {
    id: 'sub_013',
    submitterName: 'Anonymous',
    submitterProgram: 'PhD',
    submitterBatch: '2026',
    targetName: 'Research supervisor',
    targetProgram: 'Prof.',
    targetBatch: "Don't know",
    category: 'Frustration',
    bodyText: 'My supervisor has not read a single chapter of my thesis in four months despite multiple follow-ups. I am paying fees, attending mandatory seminars, and producing work that is going into a void. How is this acceptable and what do I even do?',
    triggerFlag: 'Maybe',
    status: 'pending',
    createdAt: hoursAgo(1),
    updatedAt: hoursAgo(1),
  },
  {
    id: 'sub_014',
    submitterName: 'Anonymous',
    submitterProgram: 'MBA',
    submitterBatch: '2026',
    targetName: 'A library regular',
    targetProgram: 'MBA',
    targetBatch: '2026',
    category: 'Other',
    bodyText: 'There is someone in the library who takes calls on full volume every single day in the silent zone. Everyone stares. Nobody says anything. I once accidentally made eye contact with them while they were on a call and they stared back without breaking the call. This is their domain now. We are guests.',
    triggerFlag: 'No',
    status: 'approved',
    createdAt: hoursAgo(10),
    updatedAt: hoursAgo(9),
    approvedAt: hoursAgo(9),
  },
]

export const seedSubmissions: Submission[] = raw.map((s) => {
  const { riskLevel, flags } = analyzeRisk(s.bodyText, s.triggerFlag)
  return { ...s, riskLevel, moderationFlags: flags }
})
