import type { Template, PostCategory } from './types'

export const defaultTemplates: Template[] = [
  {
    id: 'scrapbook',
    name: 'Scrapbook',
    description: 'Torn paper craft aesthetic with tape strips and handwritten feel',
    thumbnailClass: 'bg-amber-50',
    component: 'ScrapbookTemplate',
    themes: [
      { id: 'craft', name: 'Craft Paper', colors: { background: '#f5e6c8', primary: '#8b5e3c', secondary: '#c4956a', text: '#3d2b1f', accent: '#e07b39' } },
      { id: 'pastel', name: 'Pastel', colors: { background: '#fdf4f0', primary: '#d4888a', secondary: '#f7c5c5', text: '#4a2c2a', accent: '#f0a090' } },
    ],
    defaultTheme: 'craft',
    isEnabled: true,
    defaultForCategories: ['Confession', 'Other'],
  },
  {
    id: 'bold-card',
    name: 'Bold Card',
    description: 'Clean white card with bold typography and pill badges',
    thumbnailClass: 'bg-white',
    component: 'BoldCardTemplate',
    themes: [
      { id: 'classic', name: 'Classic', colors: { background: '#ffffff', primary: '#111827', secondary: '#6b7280', text: '#111827', accent: '#4f46e5' } },
      { id: 'dark', name: 'Dark Mode', colors: { background: '#111827', primary: '#f9fafb', secondary: '#9ca3af', text: '#f9fafb', accent: '#818cf8' } },
      { id: 'purple', name: 'Purple', colors: { background: '#f5f3ff', primary: '#4c1d95', secondary: '#7c3aed', text: '#1e1b4b', accent: '#8b5cf6' } },
    ],
    defaultTheme: 'classic',
    isEnabled: true,
    defaultForCategories: ['Gossip', 'Advice'],
  },
  {
    id: 'journal',
    name: 'Journal',
    description: 'Soft textured journal page with serif font and subtle ruled lines',
    thumbnailClass: 'bg-stone-50',
    component: 'JournalTemplate',
    themes: [
      { id: 'ivory', name: 'Ivory', colors: { background: '#fdfaf4', primary: '#44403c', secondary: '#78716c', text: '#292524', accent: '#a16207' } },
      { id: 'slate', name: 'Slate', colors: { background: '#f1f5f9', primary: '#334155', secondary: '#64748b', text: '#0f172a', accent: '#0ea5e9' } },
    ],
    defaultTheme: 'ivory',
    isEnabled: true,
    defaultForCategories: ['Good/Bad Experiences', 'Feedback'],
  },
  {
    id: 'handwritten',
    name: 'Handwritten',
    description: 'Minimal poster with hand-drawn style borders and casual type',
    thumbnailClass: 'bg-zinc-50',
    component: 'HandwrittenTemplate',
    themes: [
      { id: 'minimal', name: 'Minimal', colors: { background: '#fafafa', primary: '#18181b', secondary: '#71717a', text: '#18181b', accent: '#f97316' } },
      { id: 'warm', name: 'Warm', colors: { background: '#fffbeb', primary: '#92400e', secondary: '#b45309', text: '#451a03', accent: '#f59e0b' } },
    ],
    defaultTheme: 'minimal',
    isEnabled: true,
    defaultForCategories: ['Frustration', 'Horror Story / Weird Experiences'],
  },
  {
    id: 'framed-note',
    name: 'Framed Note',
    description: 'Clean note card with an elegant double-line frame',
    thumbnailClass: 'bg-neutral-50',
    component: 'FramedNoteTemplate',
    themes: [
      { id: 'linen', name: 'Linen', colors: { background: '#faf9f6', primary: '#374151', secondary: '#9ca3af', text: '#1f2937', accent: '#6b7280' } },
      { id: 'rose', name: 'Rose', colors: { background: '#fff1f2', primary: '#9f1239', secondary: '#e11d48', text: '#4c0519', accent: '#fb7185' } },
    ],
    defaultTheme: 'linen',
    isEnabled: true,
    defaultForCategories: [],
  },
  {
    id: 'confession',
    name: 'Confession',
    description: 'Dark moody template with red accents for dramatic statements',
    thumbnailClass: 'bg-gray-900',
    component: 'ConfessionTemplate',
    themes: [
      { id: 'noir', name: 'Noir', colors: { background: '#0a0a0a', primary: '#ef4444', secondary: '#991b1b', text: '#f5f5f5', accent: '#dc2626' } },
      { id: 'midnight', name: 'Midnight', colors: { background: '#0f172a', primary: '#7c3aed', secondary: '#4c1d95', text: '#e2e8f0', accent: '#a855f7' } },
    ],
    defaultTheme: 'noir',
    isEnabled: true,
    defaultForCategories: ['Horror Story / Weird Experiences'],
  },
  {
    id: 'polaroid',
    name: 'Polaroid',
    description: 'Vintage photo-card with pin, drop shadow, and handwritten feel',
    thumbnailClass: 'bg-amber-100',
    component: 'PolaroidTemplate',
    themes: [
      { id: 'vintage', name: 'Vintage', colors: { background: '#f5f0e8', primary: '#5c4a3a', secondary: '#9c8b7a', text: '#3a2d22', accent: '#c17f59' } },
      { id: 'ocean', name: 'Ocean', colors: { background: '#e8f4f8', primary: '#1a5276', secondary: '#5dade2', text: '#154360', accent: '#2e86c1' } },
      { id: 'blush', name: 'Blush', colors: { background: '#fdf2f8', primary: '#9b2c6d', secondary: '#d4a5c1', text: '#4a1a3a', accent: '#e74c8c' } },
    ],
    defaultTheme: 'vintage',
    isEnabled: true,
    defaultForCategories: ['Confession'],
  },
  {
    id: 'neon-glow',
    name: 'Neon Glow',
    description: 'Dark futuristic layout with glowing neon accents and ambient light',
    thumbnailClass: 'bg-gray-950',
    component: 'NeonGlowTemplate',
    themes: [
      { id: 'cyber', name: 'Cyber', colors: { background: '#0a0a1a', primary: '#00f5d4', secondary: '#4a5568', text: '#e2e8f0', accent: '#00f5d4' } },
      { id: 'synthwave', name: 'Synthwave', colors: { background: '#0d0221', primary: '#ff6ec7', secondary: '#7b6c8e', text: '#f0e6ff', accent: '#ff6ec7' } },
      { id: 'matrix', name: 'Matrix', colors: { background: '#000a00', primary: '#00ff41', secondary: '#4a6741', text: '#c8ffc8', accent: '#00ff41' } },
    ],
    defaultTheme: 'cyber',
    isEnabled: true,
    defaultForCategories: ['Gossip'],
  },
  {
    id: 'gradient-wave',
    name: 'Gradient Wave',
    description: 'Vibrant gradient background with white text and wave decorations',
    thumbnailClass: 'bg-gradient-to-br from-purple-500 to-pink-500',
    component: 'GradientWaveTemplate',
    themes: [
      { id: 'sunset', name: 'Sunset', colors: { background: '#ff6b6b', primary: '#c92a2a', secondary: '#ffa8a8', text: '#ffffff', accent: '#ff922b' } },
      { id: 'ocean', name: 'Ocean', colors: { background: '#1c7ed6', primary: '#1864ab', secondary: '#74c0fc', text: '#ffffff', accent: '#22b8cf' } },
      { id: 'purple', name: 'Purple', colors: { background: '#7950f2', primary: '#5f3dc4', secondary: '#b197fc', text: '#ffffff', accent: '#e64980' } },
      { id: 'forest', name: 'Forest', colors: { background: '#2b8a3e', primary: '#1b5e28', secondary: '#8ce99a', text: '#ffffff', accent: '#fab005' } },
    ],
    defaultTheme: 'sunset',
    isEnabled: true,
    defaultForCategories: [],
  },
  {
    id: 'minimal-quote',
    name: 'Minimal Quote',
    description: 'Ultra-clean design with large decorative quotation marks',
    thumbnailClass: 'bg-stone-50',
    component: 'MinimalQuoteTemplate',
    themes: [
      { id: 'clean', name: 'Clean', colors: { background: '#ffffff', primary: '#1a1a1a', secondary: '#999999', text: '#1a1a1a', accent: '#e63946' } },
      { id: 'cream', name: 'Cream', colors: { background: '#faf8f5', primary: '#2d2a26', secondary: '#8a8580', text: '#2d2a26', accent: '#b07d4f' } },
      { id: 'dark', name: 'Dark', colors: { background: '#1a1a1a', primary: '#f5f5f5', secondary: '#666666', text: '#f5f5f5', accent: '#e63946' } },
    ],
    defaultTheme: 'clean',
    isEnabled: true,
    defaultForCategories: ['Advice'],
  },
  {
    id: 'retro-vintage',
    name: 'Retro Vintage',
    description: '70s-inspired with rounded cards, sunburst lines, and warm retro tones',
    thumbnailClass: 'bg-orange-100',
    component: 'RetroVintageTemplate',
    themes: [
      { id: 'groovy', name: 'Groovy', colors: { background: '#fef3c7', primary: '#b45309', secondary: '#92400e', text: '#ffffff', accent: '#dc2626' } },
      { id: 'mint', name: 'Mint', colors: { background: '#d1fae5', primary: '#065f46', secondary: '#047857', text: '#ffffff', accent: '#f59e0b' } },
      { id: 'lavender', name: 'Lavender', colors: { background: '#ede9fe', primary: '#5b21b6', secondary: '#6d28d9', text: '#ffffff', accent: '#ec4899' } },
    ],
    defaultTheme: 'groovy',
    isEnabled: true,
    defaultForCategories: [],
  },
  {
    id: 'chalkboard',
    name: 'Chalkboard',
    description: 'Dark chalkboard texture with chalk-style text and wooden frame',
    thumbnailClass: 'bg-green-950',
    component: 'ChalkboardTemplate',
    themes: [
      { id: 'green', name: 'Green Board', colors: { background: '#1a3a2a', primary: '#2d5a3f', secondary: '#5a8a6a', text: '#e8dcc8', accent: '#fbbf24' } },
      { id: 'black', name: 'Blackboard', colors: { background: '#1a1a1e', primary: '#2a2a2e', secondary: '#5a5a5e', text: '#e0ddd5', accent: '#f87171' } },
      { id: 'navy', name: 'Navy', colors: { background: '#0f1729', primary: '#1e293b', secondary: '#475569', text: '#e2e8f0', accent: '#60a5fa' } },
    ],
    defaultTheme: 'green',
    isEnabled: true,
    defaultForCategories: ['Frustration'],
  },
]
