import type { Template, PostCategory } from './types'

export const defaultTemplates: Template[] = [
  {
    id: 'scrapbook',
    name: 'Scrapbook',
    description: 'Torn paper craft aesthetic with tape strips and handwritten feel',
    thumbnailClass: 'bg-amber-50',
    component: 'ScrapbookTemplate',
    themes: [
      { id: 'craft', name: 'Craft Paper', colors: { background: '#f5e6c8', primary: '#8b5e3c', secondary: '#c4956a', text: '#3d2b1f', accent: '#e07b39' } },
      { id: 'pastel', name: 'Pastel', colors: { background: '#fdf4f0', primary: '#d4888a', secondary: '#f7c5c5', text: '#4a2c2a', accent: '#f0a090' } },
    ],
    defaultTheme: 'craft',
    isEnabled: true,
    defaultForCategories: ['Confession', 'Other'],
  },
  {
    id: 'bold-card',
    name: 'Bold Card',
    description: 'Clean white card with bold typography and pill badges',
    thumbnailClass: 'bg-white',
    component: 'BoldCardTemplate',
    themes: [
      { id: 'classic', name: 'Classic', colors: { background: '#ffffff', primary: '#111827', secondary: '#6b7280', text: '#111827', accent: '#4f46e5' } },
      { id: 'dark', name: 'Dark Mode', colors: { background: '#111827', primary: '#f9fafb', secondary: '#9ca3af', text: '#f9fafb', accent: '#818cf8' } },
      { id: 'purple', name: 'Purple', colors: { background: '#f5f3ff', primary: '#4c1d95', secondary: '#7c3aed', text: '#1e1b4b', accent: '#8b5cf6' } },
    ],
    defaultTheme: 'classic',
    isEnabled: true,
    defaultForCategories: ['Gossip', 'Advice'],
  },
  {
    id: 'journal',
    name: 'Journal',
    description: 'Soft textured journal page with serif font and subtle ruled lines',
    thumbnailClass: 'bg-stone-50',
    component: 'JournalTemplate',
    themes: [
      { id: 'ivory', name: 'Ivory', colors: { background: '#fdfaf4', primary: '#44403c', secondary: '#78716c', text: '#292524', accent: '#a16207' } },
      { id: 'slate', name: 'Slate', colors: { background: '#f1f5f9', primary: '#334155', secondary: '#64748b', text: '#0f172a', accent: '#0ea5e9' } },
    ],
    defaultTheme: 'ivory',
    isEnabled: true,
    defaultForCategories: ['Good/Bad Experiences', 'Feedback'],
  },
  {
    id: 'handwritten',
    name: 'Handwritten',
    description: 'Minimal poster with hand-drawn style borders and casual type',
    thumbnailClass: 'bg-zinc-50',
    component: 'HandwrittenTemplate',
    themes: [
      { id: 'minimal', name: 'Minimal', colors: { background: '#fafafa', primary: '#18181b', secondary: '#71717a', text: '#18181b', accent: '#f97316' } },
      { id: 'warm', name: 'Warm', colors: { background: '#fffbeb', primary: '#92400e', secondary: '#b45309', text: '#451a03', accent: '#f59e0b' } },
    ],
    defaultTheme: 'minimal',
    isEnabled: true,
    defaultForCategories: ['Frustration', 'Horror Story / Weird Experiences'],
  },
  {
    id: 'framed-note',
    name: 'Framed Note',
    description: 'Clean note card with an elegant double-line frame',
    thumbnailClass: 'bg-neutral-50',
    component: 'FramedNoteTemplate',
    themes: [
      { id: 'linen', name: 'Linen', colors: { background: '#faf9f6', primary: '#374151', secondary: '#9ca3af', text: '#1f2937', accent: '#6b7280' } },
      { id: 'rose', name: 'Rose', colors: { background: '#fff1f2', primary: '#9f1239', secondary: '#e11d48', text: '#4c0519', accent: '#fb7185' } },
    ],
    defaultTheme: 'linen',
    isEnabled: true,
    defaultForCategories: [],
  },
  {
    id: 'confession',
    name: 'Confession',
    description: 'Dark moody template with red accents for dramatic statements',
    thumbnailClass: 'bg-gray-900',
    component: 'ConfessionTemplate',
    themes: [
      { id: 'noir', name: 'Noir', colors: { background: '#0a0a0a', primary: '#ef4444', secondary: '#991b1b', text: '#f5f5f5', accent: '#dc2626' } },
      { id: 'midnight', name: 'Midnight', colors: { background: '#0f172a', primary: '#7c3aed', secondary: '#4c1d95', text: '#e2e8f0', accent: '#a855f7' } },
    ],
    defaultTheme: 'noir',
    isEnabled: true,
    defaultForCategories: ['Horror Story / Weird Experiences'],
  },
]
